# Generated by Django 5.0 on 2024-06-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaitypes",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
