# Generated by Django 5.0 on 2024-06-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0002_chaitypes_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaitypes",
            name="price",
            field=models.CharField(default="100", max_length=3),
        ),
    ]
